#!/usr/bin/env python3

import sys
from subprocess import call


def apt_update():
    status = call([
        'apt',
        'update',
    ])
    return status


def apt_dist_upgrade():
    status = call([
        'apt',
        'dist-upgrade',
        '--yes'
    ])
    return status


def apt_autoremove():
    status = call([
        'apt',
        'autoremove',
        '--purge',
        '--yes',
    ])
    return status


def handle_status(status):
    if status != 0:
        sys.exit(status)


def main():
    status = apt_update()
    handle_status(status)

    status = apt_dist_upgrade()
    handle_status(status)

    status = apt_autoremove()
    handle_status(status)

    sys.exit(0)


if __name__ == '__main__':
    main()
