#!/usr/bin/env python3

import sys
from subprocess import call


def tdnf():
    status = call([
        'tdnf',
        'update',
        '--refresh',
        '--best',
        '--allowerasing',
        '-y'
    ])
    return status


def handle_status(status):
    if status != 0:
        sys.exit(status)


def main():
    status = tdnf()
    handle_status(status)

    sys.exit(0)


if __name__ == '__main__':
    main()
